name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  IMAGE_NAME: base

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build and push base Docker images
        uses: docker/build-push-action@v1
        with:
          path: ./base
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository:  redspot/base
          tag_with_ref: true

      - name: Build and push contract Docker images
        uses: docker/build-push-action@v1
        with:
          path: ./contract
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository:  redspot/contract
          tag_with_ref: true
